Add initial jutut instructions
apluslms/aplus-manual pull request #55
Opened 2022-06-14 07:15 UTC by joni-toivonen

Fixes #38

# Description

**What?**

[ANSWER HERE]

**Why?**

[ANSWER HERE]

**How?**

[ANSWER HERE]

Fixes #<issue number>

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-06-28 17:41 UTC, PasiSa reviewed
The text looks good to me (with couple of small suggestions). If we don't have one already, we should have some sort of acknowledgments section to credit those who have provided input to the manual.

2022-06-28 17:41 UTC, PasiSa commented on jutut/introduction.rst
> +Jutut (officially MOOC-Jutut) is a tool that enables teachers to **collect feedback continuously** during a course, to prompt students to **comment on specific parts of course content**, and to encou
As discussed in an earlier meeting, should we just start using "Jutut" consistently everywhere, and drop "MOOC-Jutut" entirely, as seems to be done in the rest of the text? If so, I suggest to drop the comment inside parenthesis.

"It is an add-on service for A+" is a short sentence that starts with "It". Pehaps remove, and consider modifiying the first sentence to "Jutut is an add-on service for A+ that enables..."

2022-06-28 18:43 UTC, Mankro commented
> The text looks good to me (with couple of small suggestions). If we don't have one already, we should have some sort of acknowledgments section to credit those who have provided input to the manual.

Acknowledgements for the whole project are here:
https://apluslms.github.io/about/authors/
It combines people from all components include the Aplus-manual repo.

2022-08-11 16:18 UTC, Mankro requested changes
Thanks! I will make small changes and merge this pull request.

2022-08-11 16:18 UTC, Mankro commented on conf.py
> +        'url': ('http://jutut:8082/feedback/testcoursemultilang/{key}' if on_container
I will change the hardcoded course key. `testcoursemultilang` does not match Aplus-manual.

2022-08-11 16:18 UTC, Mankro commented on conf.py
> +                else 'https://jutut.minus.cs.aalto.fi/feedback/testcoursemultilang/{key}'),
`jutut.minus.cs.aalto.fi`: I will change this URL too since now it refers to a testing environment.

2022-08-11 16:18 UTC, Mankro commented on docker-compose.yml
> +    image: apluslms/run-mooc-jutut:2.3.0
```suggestion
    image: apluslms/run-mooc-jutut:2.4
```
Newer image.

2022-08-11 16:18 UTC, Mankro commented on index.rst
> +  jutut/index
I think I could move the Jutut module a bit higher (earlier in the manual) so that it is easier to see in the table of contents.

2022-08-11 16:18 UTC, markkuriekkinen commented on jutut/index.rst
> +===========
```suggestion
Jutut
=====
```

2022-08-11 16:18 UTC, markkuriekkinen commented on jutut/introduction.rst
> +Jutut (officially MOOC-Jutut) is a tool that enables teachers to **collect feedback continuously** during a course, to prompt students to **comment on specific parts of course content**, and to encou
There must be a heading at the start of the chapter!

2022-08-11 16:18 UTC, Mankro commented on jutut/introduction.rst
> +  :title: MOOC-Jutut-testipalautekysely
I will translate the questionnaire contents to English.

2022-08-12 17:41 UTC, Mankro approved these changes
I made changes myself and now I will merge this pull request.

2022-08-12 17:41 UTC, merged