Update the LTI documentation to cover LTI 1.3
apluslms/aplus-manual pull request #64
Opened 2023-08-13 16:47 UTC by PasiSa

Also, the earlier LTI 1.3 Tool documentation was moved from a separate chapter at the end of the document as a subchapter along with other LTI documentation.

# Description

**What?**

[ANSWER HERE]

**Why?**

[ANSWER HERE]

**How?**

[ANSWER HERE]

Fixes #<issue number>

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-08-15 10:11 UTC, ihalaij1 requested changes
I pointed out some improvements to sentences and grammar errors. Otherwise, looks good!

2023-08-15 10:11 UTC, ihalaij1 commented on lti/configuration.rst
> +exercise referring to a Moodle activity used as A+ exercise.
I would prefer the wording like this:
A definition for an embedded LTI 1.3 exercise could _**look as follows**_, for an
exercise referring to a Moodle activity used as _**an**_ A+ exercise.

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +supports all these versions, but LTI 1.3 should be preferred when possible, as
Missing "of":
...A+ supports all _**of**_ these versions...

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +the earlier versions technically incompatible with it and are expected to be
Missing "are":
...the earlier versions _**are**_ technically incompatible...

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +implementation was introduced in A+ version 1.18).
Was LTI 1.3 Tool implementation introduced in A+ version 1.18 or 1.19?

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +  For LTI exercises number of submissions cannot be tracked, and some LTI Tools
Missing "the":
For LTI exercises, _**the**_ number of submissions cannot be tracked...

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +  student, that is based on most recent score update received from the Tool for
Missing "the":
...that is based on _**the**_ most recent score update...

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +Tool Consumer part of LTI 1.1 and 1.0. Technically these are separate
There should be a comma after "Technically".

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +implementations in A+, and are configured in different way.
Missing "a":
...are configured in _**a**_ different way.

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +  explicitly include these data fields, A+ can not track them completely
can not -> cannot

2023-08-15 10:11 UTC, ihalaij1 commented on lti/introduction.rst
> +  student uploads the submission, then A+ may track the correct number of
Improved sentence:
...the requests are sent quickly without _**a**_ delay _**when**_ the student uploads the submission...

2023-08-15 12:21 UTC, PasiSa commented on lti/introduction.rst
> +implementation was introduced in A+ version 1.18).
> Was LTI 1.3 Tool implementation introduced in A+ version 1.18 or 1.19?

It was first introduced already in 1.18, but has not actually been used yet on any course in production.

2023-08-15 12:29 UTC, PasiSa commented
Thanks Jimmy! Force pushed a fixed version.

2023-08-15 13:03 UTC, ihalaij1 approved these changes

2023-09-23 21:05 UTC, Mankro approved these changes
Excellent writing!

2023-09-23 21:05 UTC, markkuriekkinen commented on lti/introduction.rst
> +from an A+ as an LTI Tool to another LMS acting as the LTI platform. Currently
an A+?
Bad grammar?

2023-09-23 21:05 UTC, markkuriekkinen commented on lti/introduction.rst
> +repository contains a separate document about LTI configuration for A+
This could contain a link to the "separate document" for admins.

https://github.com/apluslms/a-plus/blob/master/doc/LTI_1.3_PLATFORM.md
https://github.com/apluslms/a-plus/blob/master/doc/LTI_TOOL.md

2023-09-23 21:05 UTC, markkuriekkinen commented on lti/configuration.rst
> +repository.
Link https://github.com/apluslms/a-plus/blob/master/doc/LTI_1.3_PLATFORM.md

2023-09-23 21:05 UTC, merged